/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AuthPopup: typeof import('./../src/components/popups/AuthPopup.vue')['default']
    ClaimCard: typeof import('./../src/components/ui/ClaimCard.vue')['default']
    ClaimPopup: typeof import('./../src/components/popups/ClaimPopup.vue')['default']
    InvalidNetworkPopup: typeof import('./../src/components/popups/InvalidNetworkPopup.vue')['default']
    Motion: typeof import('./../src/components/motion/index.vue')['default']
    NotificationList: typeof import('./../src/components/ui/NotificationList.vue')['default']
    NotificationListItem: typeof import('./../src/components/ui/NotificationListItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheButton: typeof import('./../src/components/ui/TheButton.vue')['default']
    TheCard: typeof import('./../src/components/ui/TheCard.vue')['default']
    TheCircle: typeof import('./../src/components/animated/TheCircle.vue')['default']
    TheFooter: typeof import('./../src/components/TheFooter.vue')['default']
    TheHeader: typeof import('./../src/components/TheHeader.vue')['default']
    TheLoader: typeof import('./../src/components/animated/TheLoader.vue')['default']
    ThePlayer: typeof import('./../src/components/ui/ThePlayer.vue')['default']
    ThePopup: typeof import('./../src/components/ui/ThePopup.vue')['default']
    TheTimer: typeof import('./../src/components/TheTimer.vue')['default']
    TheTournament: typeof import('./../src/components/ui/TheTournament/TheTournament.vue')['default']
    TheTournamentStats: typeof import('./../src/components/ui/TheTournament/TheTournamentStats.vue')['default']
    TheTournamentStatus: typeof import('./../src/components/ui/TheTournament/TheTournamentStatus.vue')['default']
    TokenAmounts: typeof import('./../src/components/ui/TokenAmounts/TokenAmounts.vue')['default']
    TokenAmountsChart: typeof import('./../src/components/ui/TokenAmounts/TokenAmountsChart.vue')['default']
    TokenAmountsList: typeof import('./../src/components/ui/TokenAmounts/TokenAmountsList.vue')['default']
    TokenChampion: typeof import('./../src/components/ui/TokenSwap/TokenChampion.vue')['default']
    TokenIcon: typeof import('./../src/components/ui/TokenIcon.vue')['default']
    TokenIconCircle: typeof import('./../src/components/ui/TokenIconCircle.vue')['default']
    TokenPrices: typeof import('./../src/components/ui/TokenPrices/TokenPrices.vue')['default']
    TokenPricesItem: typeof import('./../src/components/ui/TokenPrices/TokenPricesItem.vue')['default']
    TokenSelect: typeof import('./../src/components/ui/TokenSelect.vue')['default']
    TokenSelectPopup: typeof import('./../src/components/popups/TokenSelectPopup.vue')['default']
    TokenSwap: typeof import('./../src/components/ui/TokenSwap/TokenSwap.vue')['default']
    TokenSwapForm: typeof import('./../src/components/ui/TokenSwap/TokenSwapForm.vue')['default']
    TokenSwapTitle: typeof import('./../src/components/ui/TokenSwap/TokenSwapTitle.vue')['default']
    TokenSwapTolerance: typeof import('./../src/components/ui/TokenSwap/TokenSwapTolerance.vue')['default']
    UserConnect: typeof import('./../src/components/ui/UserConnect.vue')['default']
    UserMenu: typeof import('./../src/components/ui/UserMenu.vue')['default']
    UserNotConnected: typeof import('./../src/components/ui/UserNotConnected.vue')['default']
  }
}
